### PR TITLE
Allow formula syntax

### PR DESCRIPTION
**Pull request by tmelliott**
I think that's all that is needed...
It'll remain backwards-compatible, but allows `x` to be a formula:

``` r
vioplotx(Sepal.Length ~ Species, data = iris)
```

Also lazy eval of `names`, so user doesn't have to worry about that (if they don't want to) and they should match up ... and if they specify vectors (old way) `names = names(datas)` evaluates to `NULL` so it should work. 

**Disclaimer**: have not tested.

### CODE REVIEW

**Comment by tmelliott** [comment]
OK so I was too clever about the lazy evaluation. I'll leave the _rest_ of the testing up to you (and the roxygen comments).

**Comment by TomKellyGenetics** [comment]
I've included formula and data in the roxygen params but I'm unsure how to include the formula syntax in usage without manually editing roxygen output.

**Comment by TomKellyGenetics** [comment]
Testing works great though. Added type checking to `data` input too, just in case.

**Comment by tmelliott** [comment]
I think most standard examples use S3 classes in this situation, so you'll have `vioplotx.default` and `vioplotx.formula`, which processes the formula and passes it to `vioplotx.default`. 

For example, take a look at `plot.default` vs `graphics:::plot.formula`. Definitely not necessary, but helps separate out the logic and forces R to do the work for you (removes the `if (inherits(...))` logic). 

But anyway, in that case the roxygen would be simpler. If not, I generally just use something along the lines of:

``` r
#' @param x a data vector, or a \code{formula} such as \code{y ~ x}.
```

**Comment by TomKellyGenetics** [comment]
Ah right, I tried to get the roxygen params to match up with `boxplot` but I couldn't get the usage field to work properly. S3 seemed the way to go but most of the package and roxygen guides seemed to assume prior knowledge of how S3 classes worked. Using and developing them are different. Interesting to be learning more though. Thanks for the pointers, I'll see what I can do with those examples.

**Comment by TomKellyGenetics** [comment]
I think this https://github.com/TomKellyGenetics/vioplotx/commit/d907f8098c92568efee7ca3ca4e330c6ee8fb7f9 has implemented `vioplot.formula` and `vioplot.default` as S3 generics as suggestde . The tests mostly run the same but it's enabled automated documentation of both input options with `roxygen2`. It took some grappling to get working but it's seem like a good thing to make a habit of :)

**Pull request merged**
